name = "claude-code-containers"
main = "src/index.ts"
compatibility_date = "2025-05-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[containers]]
class_name = "MyContainer"
image = "./Dockerfile"
max_instances = 10

[[durable_objects.bindings]]
name = "MY_CONTAINER"
class_name = "MyContainer"

[[durable_objects.bindings]]
name = "GITHUB_APP_CONFIG"
class_name = "GitHubAppConfigDO"

[[durable_objects.bindings]]
name = "USER_CONFIG"
class_name = "UserConfigDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyContainer", "GitHubAppConfigDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["UserConfigDO"]

[build]
command = "npm run build:all"

[env.production.vars]
ENVIRONMENT = "production"
ENABLE_DEEP_REASONING = "false"

[env.staging]
name = "claude-code-containers-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
ENABLE_DEEP_REASONING = "false"

[env.development]
name = "claude-code-containers-dev"

[env.development.vars]
ENVIRONMENT = "development"
ENABLE_DEEP_REASONING = "false"