openapi: 3.0.3
info:
  title: ACP Bridge API
  version: 0.1.0
  description: Minimal API surface for Zed ACP bridge (Worker endpoints)
servers:
  - url: https://{{worker_host}}
paths:
  /acp/initialize:
    post:
      summary: Initialize an ACP session (register agent)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agentId:
                  type: string
                capabilities:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Session created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  sessionId:
                    type: string
  /acp/task/execute:
    post:
      summary: Execute ACP task message; forwards mapped payloads to container
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Acknowledged / forwarded
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  forwarded:
                    type: boolean
                  status:
                    type: integer
  /acp/status:
    get:
      summary: Get bridge status and active sessions
      responses:
        '200':
          description: Current sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  sessions:
                    type: array
                    items:
                      type: object
                      properties:
                        sessionId:
                          type: string
                        agentId:
                          type: string

  /acp/rpc:
    post:
      summary: Generic JSON-RPC endpoint for ACP methods (initialize, session/new, session/prompt, etc.)
      description: |
        Accepts a JSON-RPC 2.0 envelope. This endpoint is the recommended first-step for ACP compatibility.
        For streaming session.load and incremental session.update messages, implement `/acp/ws` WebSocket upgrade (see quickstart).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                id:
                  oneOf:
                    - type: string
                    - type: integer
                method:
                  type: string
                params:
                  type: object
      responses:
        '200':
          description: JSON-RPC response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: "2.0"
                  id:
                    oneOf:
                      - type: string
                      - type: integer
                  result:
                    type: object
                  error:
                    type: object

x-websocket-note: |
  For full ACP compatibility, the Worker should support a WebSocket upgrade at `/acp/ws` that transports JSON-RPC messages bidirectionally. OpenAPI has limited WS support; document the WS protocol here and in `quickstart.md`.
